K: 4
G: 100
nr_of_training_cases: 1000000
epsilon: 0.0
epochs: 100
negative_training_power: 20 #The higher this number, the less relative training will the inferior networks receive.
                            #Value of zero gives linearly decreasing number of training episodes.

load_best_policy: True

load_reinforcement: True
