K: 8
G: 500
nr_of_training_cases: 100000
epsilon: 0.0
epochs: 1000
negative_training_power: 10 #The higher this number, the less relative training will the inferior networks receive.
                            #Value of zero gives linearly decreasing number of training episodes.

load_best_policy: False

load_reinforcement: True